mykisik/mykisik/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('captcha/', include('captcha.urls')),
    path('', include('news.urls')),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mykisik/news/urls.py
from django.urls import path

# from django.views.decorators.cache import cache_page
from .views import HomeNews, NewsByCategry, AddNews, add_comment, news_detail

urlpatterns = [
    path("", HomeNews.as_view(), name="home"),
    path(
        "category/<int:category_id>/", NewsByCategry.as_view(), name="category"
    ),
    path("news/<int:news_id>/", news_detail, name="detail_news"),
    path("news/add_news/", AddNews.as_view(), name="add_news"),
    path("news/<int:news_id>/comment/", add_comment, name="add_comment"),
]

mykisik/users/urls.py
from django.contrib.auth import views as v
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
    path(
        "logout/",
        v.LogoutView.as_view(template_name="users/logged_out.html"),
        name="logout",
    ),
    path(
        "login/",
        v.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "password_change",
        v.PasswordChangeView.as_view(
            template_name="users/password_change_form.html"
        ),
        name="password_change",
    ),
    path(
        "password_change/done",
        v.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        v.PasswordResetView.as_view(
            template_name="users/password_reset_form.html"
        ),
        name="password_reset_form",
    ),
    path(
        "password_reset/done",
        v.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
]

mykisik/news/models.py
from django.db import models
from django.urls import reverse


class News(models.Model):
    title = models.CharField(max_length=150, verbose_name="Наименование")
    content = models.TextField(blank=True, verbose_name="Информация")
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата публикации"
    )
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Обновленно")
    photo = models.ImageField(
        upload_to="photos/%Y/%m/%d/", verbose_name="Фото", blank=True
    )
    is_published = models.BooleanField(
        default=True, verbose_name="Опубликованно"
    )
    category = models.ForeignKey(
        "Category", on_delete=models.PROTECT, verbose_name="Категория"
    )

    def get_absolute_url(self):
        return reverse("detail_news", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = "новость"
        verbose_name_plural = "новости"
        ordering = ["-created_at"]


class Category(models.Model):
    title = models.CharField(
        max_length=150, db_index=True, verbose_name="Наименование категории"
    )
    slug = models.SlugField(
        max_length=50, unique=True, db_index=True, verbose_name="URL"
    )

    def get_absolute_url(self):
        return reverse("category", kwargs={"category_id": self.pk})

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = "категорию"
        verbose_name_plural = "категории"
        ordering = ["title"]


class Comment(models.Model):
    news = models.ForeignKey(
        News,
        on_delete=models.CASCADE,
        related_name="comments",
    )
    text = models.TextField()
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата публикации"
    )

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "комментарий"
        verbose_name_plural = "Комментарии"

mykisik/news/forms.py
from django import forms
from django.core.exceptions import ValidationError
import re
from captcha.fields import CaptchaField

from .models import Comment, News


class NewsForm(forms.ModelForm):
    """При создании или редактировании поста в поле группы, при отсутствии
    выбора, содержит сообщение -- Группа не выбрана --"""

    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["category"].empty_label = "-- Категория не выбрана --"

    class Meta:
        model = News
        fields = ["title", "content", "is_published", "photo", "category"]
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "content": forms.Textarea(
                attrs={"class": "form-control", "rows": 5}
            ),
            "photo": forms.FileInput(attrs={"class": "form-control"}),
            "category": forms.Select(attrs={"class": "form-control"}),
        }

    def clean_title(self):
        title = self.cleaned_data["title"]
        if re.match(r"\d", title):
            raise ValidationError("Название не должно начинаться с цифры")
        elif len(title) > 100:
            raise ValidationError("Длина превышает 100 символов")
        return title


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]
        labels = {"text": "Текст комментария"}
        help_texts = {"text": "Введите текст комментария"}

mykisik/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from captcha.fields import CaptchaField


User = get_user_model()


class CreationForm(UserCreationForm):
    captcha = CaptchaField()

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

mykisik/news/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView
from django.shortcuts import render, redirect, get_object_or_404

from .models import Comment, News, Category
from .forms import CommentForm, NewsForm


class HomeNews(ListView):
    paginate_by = 3
    model = News
    template_name = "news/home_news_list.html"
    context_object_name = "news"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Главная страница"
        return context

    def get_queryset(self):
        return News.objects.filter(is_published=True).select_related(
            "category"
        )


class NewsByCategry(ListView):
    paginate_by = 3
    model = News
    template_name = "news/home_news_list.html"
    context_object_name = "news"
    allow_empty = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Категория: " + str(
            Category.objects.get(pk=self.kwargs["category_id"])
        )
        return context

    def get_queryset(self):
        return News.objects.filter(
            category_id=self.kwargs["category_id"], is_published=True
        ).select_related("category")


def news_detail(request, news_id):
    news = get_object_or_404(News, id=news_id)
    title = news.content[:30]
    form = CommentForm()
    comments = Comment.objects.filter(news_id=news_id)
    template = "news/detail_news.html"
    context = {
        "news": news,
        "title": title,
        "form": form,
        "comments": comments,
    }
    return render(request, template, context)


class AddNews(LoginRequiredMixin, CreateView):
    form_class = NewsForm
    template_name = "news/add_news.html"
    success_url = reverse_lazy("home")

    # success_url = reverse_lazy('detail_news', kwargs={'pk': news.pk})
    # Пока не работает


def add_comment(request, news_id):
    news = News.objects.get(pk=news_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.news = news
        comment.save()
    return redirect("detail_news", news_id=news_id)

mykisik/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('home')
    template_name = 'users/signup.html'

mykisik/templates/base.html
{% load static %}
<!doctype html>
<html lang="ru" dir="ltl">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet"
          href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static '/style.css' %}"/>
    <title>
      {% block title %}
        Спаси жизнь
      {% endblock title %}
    </title>
    <link rel="shortcut icon"
          type="image/png"
          href="{% static "img/fav/favicon.ico" %}"/>
  </head>
  <body>
    {% include "inc/_nav.html" %}
    <div class="container mt-3">
      <div class="row">
        {% block sidebar %}
        {% endblock sidebar %}
        {% block content %}
          CONTENT
        {% endblock content %}
        {% if page_obj.has_other_pages %}
          <nav class="Paginator" aria-label="Page navigation example">
            <ul class="pagination pagination-lg justify-content-center">
              {% if page_obj.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?page=1">Первая</a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lt</a>
                </li>
              {% endif %}
              {% for p in paginator.page_range %}
                {% if page_obj.number == p %}
                  <li class="page-item active">
                    <span class="page-link">{{ p }}</span>
                  </li>
                {% else %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                  </li>
                {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.next_page_number }}">&gt</a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
                </li>
              {% endif %}
            </ul>
          </nav>
        {% endif %}
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script scr="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

mykisik/templates/inc/_nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">
      <img src="{% static 'img/logo.png' %}"
           width="40"
           height="40"
           class="d-inline-block align-top"
           alt=""/>
    </a>
    <a href="{% url 'home' %}" class="nav-link2">MYKISIK</a>
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url 'home' %}" class="nav-link">Главная</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'add_news' %}" class="nav-link">Новая запись</a>
          </li>
          <li class="nav-item">
            <a class="nav-link  {% if view_name == 'users:logout' %}active{% endif %}"
               href="{% url 'users:logout' %}">Выйти</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link  {% if view_name == 'users:login' %}active{% endif %}"
               href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'users:signup' %}active{% endif %}"
               href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

mykisik/templates/inc/_sidebar.html
{% load news_tags %}
<div class="col-md-3">
    <h5>Категории:</h5>
    <div class="list-group">{% show_categories %}</div>
</div>
<br/>

mykisik/templates/news/add_news.html
{% extends "base.html" %}
{% block title %}
    Добавление новости
{% endblock title %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    <h3>Добавление новости</h3>
                </div>
                <div class="card-body">
                    <form action="{% url 'add_news' %}"
                          method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary btn-block">Добавить новость</button>
                            <div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endblock content %}

mykisik/templates/news/category.html
{% extends "base.html" %}
{% block title %}
  {{ category.title }} {{ block.super }}
{% endblock title %}
{% block sidebar %}
  {% include "inc/_sidebar.html" %}
{% endblock sidebar %}
{% block content %}
  {% for item in news %}
    <div class="card mb-3">
      <div class="card-header">Категория: {{ item.category.title }}</div>
      <div class="card-body">
        <div class="media">
          {% if item.photo %}
            <img src="{{ item.photo.url }}"
                 alt=""
                 width="350"
                 class="me-3 float-start"/>
          {% else %}
            <img src="https://picsum.photos/id/237/350/300"
                 alt=""
                 class="me-3 float-start"/>
          {% endif %}
          <div class="media-body">
            <h5 class="card-title {% cycle 'text-danger' 'text-danger' %}">{{ item.title }}</h5>
            <p class="card-text">{{ item.content|linebreaks }}</p>
            <a href="{{ item.get_absolute_url }}" class="btn btn-primary">Read more...</a>
          </div>
        </div>
      </div>
      <div class="card-footer text-muted">{{ item.created_at|date:"Y-m-d H:i:s" }}</div>
    </div>
  {% endfor %}
{% endblock content %}

mykisik/templates/news/detail_news.html
{% extends "base.html" %}
{% block title %}
  {{ news.category.title }} {{ block.super }}
{% endblock title %}
{% block sidebar %}
  {% include "inc/_sidebar.html" %}
{% endblock sidebar %}
{% load user_filters %}
{% load thumbnail %}
{% block content %}
  <div class="col-md-9">
    <div class="card mb-3">
      <div>
        <a href="{% url 'category' news.category.id %}" class="card-header">Категория: {{ news.category.title }}</a>
      </div>
      <div class="card-body">
        {% thumbnail news.photo "960x960" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <h5 class="card-title {% cycle 'text-danger' 'text-danger' %}">{{ news.title }}</h5>
      <p class="card-text">{{ news.content|linebreaks }}</p>
      <div class="card my-4">
        <h3 class="card-header">Добавить комментарий:</h3>
        <div class="card-body">
          <form method="post" action="{% url 'add_comment' news.id %}">
            {% csrf_token %}
            <div class="form-group mb-2">{{ form.text|addclass:"form-control" }}</div>
            <div class="text-center">
              <button type="submit" class="btn btn-primary">Отправить</button>
            </div>
          </form>
        </div>
      </div>
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="comments">
            <h5 class="mt-0">
              <p>Комментарий пользователя:</p>
            </h5>
            <p>{{ comment.text }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
    <div class="card-footer text-muted">{{ news_item.created_at|date:"Y-m-d H:i:s" }}</div>
  </div>
</div>
{% endblock content %}

mykisik/templates/news/home_news_list.html
{% extends "base.html" %}
{% block title %}
  {{ title }} {{ block.super }}
{% endblock title %}
{% block sidebar %}
  {% include "inc/_sidebar.html" %}
{% endblock sidebar %}
{% block content %}
  <div class="col-md-9">
    <h5>Всего новостей: {{ news.count }}</h5>
    {% for item in news %}
      <div class="card mb-3">
        <div>
          {% comment %} <a href="{{ item.category.get_absolute_url }}" class="card-header">Категория: {{ item.category.title }}</a> {% endcomment %}
        </div>
        <div class="card-body">
          <div class="media">
                <img src="{{ item.photo.url }}"
                     alt=""
                     class="myimage"/>
              <div class="media-body">
                <h5 class="card-title {% cycle 'text-danger' 'text-danger' %}">{{ item.title }}</h5>
                <p class="card-text">{{ item.content|linebreaks|truncatewords:50 }}</p>
                <a href="{% url 'detail_news' item.id %}" class="btn btn-primary">Читать полностью</a>
                <h5>Комментариев: {{ item.comments.count }}</h5>
              </div>
              
          </div>

        </div>
        <div class="card-footer text-muted">{{ item.created_at|date:"Y-m-d H:i:s" }}</div>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

mykisik/templates/news/list_categories.html
<div class="list-group">
    {{ arg1 }} {{ arg2 }}
    {% for item in categories %}
        <a href="{{ item.get_absolute_url }}"
           class="list-group-item list-group-item-action">{{ item.title }}</a>
    {% endfor %}
</div>

mykisik/templates/users/logged_out.html
{% extends "base.html" %}
{% block title %}
  Вы вышли из системы
{% endblock title %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          <h3>Выход</h3>
        </div>
        <div class="card-body">
          <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

mykisik/templates/users/login.html
{% extends "base.html" %}
{% block title %}
  Войти
{% endblock title %}
{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-6 p-5">
      <div class="card">
        <div class="card-header">
          <h3>Войти на сайт</h3>
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
          {% endif %}
          <form method="post"
                {% if action_url %} action="{% url action_url %}" {% endif %}>
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3"
                   {% if field.field.required %} aria-required="true" {% else %} aria-required="false" {% endif %}>
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                </label>
                <div>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-3">
              <button type="submit" class="btn btn-primary">Войти</button>
              <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">Забыли пароль?</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

mykisik/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Войти{% endblock title %}
{% block content %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="list-group-item list-group-item-success">Пароль изменён</div>
          <div class="card-body">
            <p>Пароль изменён успешно</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

mykisik/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Войти{% endblock title %}
{% block content %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Изменить пароль</div>
          <div class="card-body">
            <form method="get" action="{% url 'users:password_change_done' %}">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_old_password">
                  Старый пароль
                  <span class="required text-danger">*</span>
                </label>
                <input type="password"
                       name="old_password"
                       autofocus
                       class="form-control"
                       required
                       id="id_old_password"/>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password1">
                  Новый пароль
                  <span class="required text-danger">*</span>
                </label>
                <input type="password"
                       name="new_password1"
                       class="form-control"
                       required
                       id="id_new_password1"/>
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul>
                    <li>
                      Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.
                    </li>
                    <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                    <li>Ваш пароль не может быть одним из широко распространённых паролей.</li>
                    <li>Ваш пароль не может состоять только из цифр.</li>
                  </ul>
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password2">
                  Подтверждение нового пароля
                  <span class="required text-danger">*</span>
                </label>
                <input type="password"
                       name="new_password2"
                       class="form-control"
                       required
                       id="id_new_password2"/>
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">Изменить пароль</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

mykisik/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Войти{% endblock title %}
{% block content %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Восстановление пароля завершено</div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="../users/login.html">войти</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

mykisik/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Войти{% endblock title %}
{% block content %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Введите новый пароль</div>
          <div class="card-body">
            <form method="post" action="../users/lpassword_reset_confirm.html">
              <input type="hidden" name="csrfmiddlewaretoken" value=""/>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password1">
                  Новый пароль
                  <span class="required text-danger">*</span>
                </label>
                <input type="password"
                       name="new_password1"
                       class="form-control"
                       required
                       id="id_new_password1"/>
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul>
                    <li>
                      Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.
                    </li>
                    <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                    <li>Ваш пароль не может быть одним из широко распространённых паролей.</li>
                    <li>Ваш пароль не может состоять только из цифр.</li>
                  </ul>
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password2">
                  Подтверждение нового пароля
                  <span class="required text-danger">*</span>
                </label>
                <input type="password"
                       name="new_password2"
                       class="form-control"
                       required
                       id="id_new_password2"/>
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">Назначить новый пароль</button>
              </div>
            </form>
          </div>
          <!-- card body -->
        </div>
        <!-- card -->
      </div>
      <!-- col -->
    </div>
    <!-- row -->
    <!-- если использована неправильная ссылка -->
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Ошибка</div>
          <div class="card-body">
            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
          </div>
          <!-- card body -->
        </div>
        <!-- card -->
      </div>
      <!-- col -->
    </div>
    <!-- row -->
    <!-- конец если использована неправильная ссылка -->
  </div>
{% endblock content %}

mykisik/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="list-group-item list-group-item-success">Отправлено письмо</div>
          <div class="card-body">
            <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

mykisik/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Войти{% endblock title %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body">
            <form method="get" action="{% url 'users:password_reset_done' %}">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_email">
                  Адрес электронной почты
                  <span class="required text-danger">*</span>
                </label>
                <input type="email"
                       name="email"
                       maxlength="254"
                       class="form-control"
                       required
                       id="id_email"/>
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">Сбросить пароль</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

mykisik/templates/users/signup.html
{% extends "base.html" %}
{% block title %}
  Зарегистрироваться
{% endblock title %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          <h3>Зарегистрироваться</h3>
        </div>
        <div class="card-body">
          {% load user_filters %}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
          {% endif %}
          <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            </div>
          </form>
        </div>
        <!-- card body -->
      </div>
      <!-- card -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
{% endblock content %}